FROM python:3-alpine
RUN apk --no-cache add bash ca-certificates curl git jq openssh && update-ca-certificates
RUN pip --no-cache-dir install "https://packages.nebula.puppet.net/sdk/support/python/v1/nebula_sdk-1-py3-none-any.whl"
RUN pip --no-cache-dir install quart

LABEL "org.opencontainers.image.title"="Core"
LABEL "org.opencontainers.image.description"="An Alpine Linux image with the Nebula SDK tools installed."
LABEL "com.puppet.nebula.sdk.version"="v1"
