FROM python:3-alpine
RUN apk --no-cache add bash ca-certificates curl git jq openssh && update-ca-certificates
RUN pip --no-cache-dir install quart
RUN pip --no-cache-dir install relay-sdk

LABEL "org.opencontainers.image.title"="Core"
LABEL "org.opencontainers.image.description"="An Alpine Linux image with the Nebula SDK tools installed."
LABEL "com.puppet.nebula.sdk.version"="v1"
